#!/bin/bash
source /etc/profile
source /etc/profile.d/grid-env.sh
source /etc/profile.d/grid-vo-env.sh
export VO_ATLAS_SW_DIR=/cvmfs/atlas.cern.ch/repo/sw
export VO_ATLAS_DEFAULT_SE=srm-atlas.cern.ch
export VO_CMS_SW_DIR=/cvmfs/cms.cern.ch
export VO_CMS_DEFAULT_SE=srm-cms.cern.ch
export GLEXEC_LOCATION=/usr
export GLITE_LOCATION=/usr
export GLITE_ENV_SET=TRUE
export GLITE_LOCATION_VAR=/var
export ATLAS_CGROUPS_BASE=/cgroup/memory
export TMPDIR=$_CONDOR_SCRATCH_DIR/tmp
# source /usr/sbin/mjf-job-wrapper
exec "$@"
error=$?
echo "Failed to exec($error): $@" > $_CONDOR_WRAPPER_ERROR_FILE
exit 1
